version: 2.1

orbs:
  cypress: cypress-io/cypress@1.26.0  
  win: circleci/windows@2.4.0
  macos: circleci/macos@1.1.0

executors:
  mac:
    macos:
      xcode: 10.1.0   
  
jobs:  
  win-test-chrome:
    working_directory: ~/app    
    executor: 
      name: win/default
    steps:
      - checkout      
      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      # install Chrome browser on Windows machine using Chocolatey
      # https://chocolatey.org/packages/GoogleChrome
      - run: choco install googlechrome
      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache
            
      - run:
          name: 'Run Cypress tests'
          command: npm run e2e:chrome -- --env circle=true
          no_output_timeout: 10m
      - store_artifacts:
          path: cypress\screenshots
      - store_artifacts:
          path: cypress\videos
      - store_artifacts:
          path: dist

  win-test-firefox:
    working_directory: ~/app
    executor: 
      name: win/default
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}

      # install Firefox browser on Windows machine using Chocolatey
      # https://chocolatey.org/packages/Firefox
      - run: choco install firefox
      - run: npm ci
      - run: npm run cy:verify
      - run: npm run cy:info

      - save_cache:
          key: dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            # could not use environment variables for some reason
            - C:\Users\circleci\AppData\Local\Cypress\Cache
            - C:\Users\circleci\AppData\Roaming\npm-cache

      - run:
          name: 'Run Cypress tests'
          command: npm run e2e:firefox
          no_output_timeout: 10m
          when: on_success
      - store_artifacts:
          path: cypress\screenshots
      - store_artifacts:
          path: cypress\videos
      - store_artifacts:
          path: dist

workflows:
  win-build:
    jobs:      
      - win-test-chrome
      - win-test-firefox

  mac-build:
    jobs:
      - cypress/install:
          name: 'Mac install'                            

      - cypress/run:
          name: Mac test
          executor: mac 
          requires:
            - Mac install            
          record: true
          parallel: true
          parallelism: 2          
          start: npm start
          wait-on: 'http://localhost:4200'          

      - cypress/run:
          name: Mac test with chrome
          executor: mac 
          requires:
            - Mac install            
          record: true
          parallel: true
          parallelism: 2
          browser: chrome
          start: npm start
          wait-on: 'http://localhost:4200'
          group: 'Mac build with chrome'